### ISSUE TITLE
Error while getting pub dependency

### ISSUE THREAD

**Issue by sureshg** [lejard-h/angular_recaptcha#1]
Created a sample angular2 app with `recaptcha` dependency as given below and is throwing the following error on `pub get`.

```yaml
environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  angular2: '>=2.2.0 <2.3.0'
  angular2_components: '>=0.2.2 <0.3.0'
  angular_recaptcha:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```

Error, 

```
Error on line 24, column 3 of ../../../.pub-cache/hosted/pub.dartlang.org/angular_recaptcha-0.0.1/pubspec.yaml: 
Error loading transformer "dart_to_js_script_rewriter": package "dart_to_js_script_rewriter" is not a dependency.
- dart_to_js_script_rewriter
  ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Pub Build
```
Loading angular2 transformers...
No matching file found for the following Angular2 transformer entry_points:
  - example/main.dart
```

**Comment by lejard-h** [comment]
you did not provide any version on `angular_recaptcha`, can you try `angular_recaptcha: 0.0.1` ?

**Comment by sureshg** [comment]
Same error for ` 0.0.1` version. You can  easily reproduce it by creating the sample angular2 app from webstorm

**Comment by lejard-h** [comment]
fixed with `0.0.2`

**Comment by sureshg** [comment]
The app is still failing with `Could not find Directive/Pipe entry for name: AngularRecaptcha` error

**Comment by lejard-h** [comment]
it should be fix with `0.0.3`, 
if not, can you create a new issue ?
